<?php

return [
    'html-blocks' => [
        "title" => "Title",
        "title1" => "Title1",
        "title2" => "Title2",
        "title3" => "Title3",
        "title4" => "Title4",
        "title5" => "Title5",
        "title6" => "Title6",
        "shortdescription1" => "ShortDescription1",
        "shortdescription2" => "ShortDescription2",
        "shortdescription3" => "ShortDescription3",
        "shortdescription4" => "ShortDescription4",
        "shortdescription5" => "ShortDescription5",
        "description1" => "Description1",
        "description2" => "Description2",
        "description3" => "Description3",
        "image1" => "Image1",
        "image2" => "Image2",
        "link1" => "Link1",
        "link2" => "Link2",
        "link3" => "Link3",
        "link4" => "Link4",
        "link5" => "Link5",
        "headerimage" => "Header Image",
        "headertext" => "Header text",
        "metatags" => "Meta tags",
        "status"    =>  "status",
    ],
    'states' => [
        ["state" => "Andhra Pradesh", "abbreviation" => "AP"],
        ["state" => "Arunachal Pradesh", "abbreviation" => "AR"],
        ["state" => "Assam", "abbreviation" => "AS"],
        ["state" => "Bihar", "abbreviation" => "BR"],
        ["state" => "Chhattisgarh", "abbreviation" => "CG"],
        ["state" => "Goa", "abbreviation" => "GA"],
        ["state" => "Gujarat", "abbreviation" => "GJ"],
        ["state" => "Haryana", "abbreviation" => "HR"],
        ["state" => "Himachal Pradesh", "abbreviation" => "HP"],
        ["state" => "Jharkhand", "abbreviation" => "JH"],
        ["state" => "Karnataka", "abbreviation" => "KA"],
        ["state" => "Kerala", "abbreviation" => "KL"],
        ["state" => "Madhya Pradesh", "abbreviation" => "MP"],
        ["state" => "Maharashtra", "abbreviation" => "MH"],
        ["state" => "Manipur", "abbreviation" => "MN"],
        ["state" => "Meghalaya", "abbreviation" => "ML"],
        ["state" => "Mizoram", "abbreviation" => "MZ"],
        ["state" => "Nagaland", "abbreviation" => "NL"],
        ["state" => "Odisha", "abbreviation" => "OR"],
        ["state" => "Punjab", "abbreviation" => "PB"],
        ["state" => "Rajasthan", "abbreviation" => "RJ"],
        ["state" => "Sikkim", "abbreviation" => "SK"],
        ["state" => "Tamil Nadu", "abbreviation" => "TN"],
        ["state" => "Telangana", "abbreviation" => "TG"],
        ["state" => "Tripura", "abbreviation" => "TR"],
        ["state" => "Uttar Pradesh", "abbreviation" => "UP"],
        ["state" => "Uttarakhand", "abbreviation" => "UK"],
        ["state" => "West Bengal", "abbreviation" => "WB"]
    ],
    'cities' => [
        ['city' => 'Mumbai', 'abbreviation' => 'MUM'],
        ['city' => 'Delhi', 'abbreviation' => 'DEL'],
        ['city' => 'Bangalore', 'abbreviation' => 'BLR'],
        ['city' => 'Hyderabad', 'abbreviation' => 'HYD'],
        ['city' => 'Ahmedabad', 'abbreviation' => 'AMD'],
        ['city' => 'Chennai', 'abbreviation' => 'CHE'],
        ['city' => 'Kolkata', 'abbreviation' => 'KOL'],
        ['city' => 'Surat', 'abbreviation' => 'SUR'],
        ['city' => 'Pune', 'abbreviation' => 'PUN'],
        ['city' => 'Jaipur', 'abbreviation' => 'JAI'],
        ['city' => 'Lucknow', 'abbreviation' => 'LKO'],
        ['city' => 'Kanpur', 'abbreviation' => 'KNP'],
        ['city' => 'Nagpur', 'abbreviation' => 'NGP'],
        ['city' => 'Visakhapatnam', 'abbreviation' => 'VIZ'],
        ['city' => 'Indore', 'abbreviation' => 'IDR'],
        ['city' => 'Thane', 'abbreviation' => 'THN'],
        ['city' => 'Bhopal', 'abbreviation' => 'BHO'],
        ['city' => 'Patna', 'abbreviation' => 'PAT'],
        ['city' => 'Vadodara', 'abbreviation' => 'VAD'],
        ['city' => 'Ghaziabad', 'abbreviation' => 'GHZ'],
        ['city' => 'Ludhiana', 'abbreviation' => 'LDH'],
        ['city' => 'Agra', 'abbreviation' => 'AGR'],
        ['city' => 'Nashik', 'abbreviation' => 'NAS'],
        ['city' => 'Faridabad', 'abbreviation' => 'FBD'],
        ['city' => 'Meerut', 'abbreviation' => 'MRT'],
        ['city' => 'Rajkot', 'abbreviation' => 'RJT'],
        ['city' => 'Kalyan-Dombivli', 'abbreviation' => 'KD'],
        ['city' => 'Vasai-Virar', 'abbreviation' => 'VV'],
        ['city' => 'Varanasi', 'abbreviation' => 'VAR'],
        ['city' => 'Srinagar', 'abbreviation' => 'SXR'],
        ['city' => 'Aurangabad', 'abbreviation' => 'AUR'],
        ['city' => 'Dhanbad', 'abbreviation' => 'DHN'],
        ['city' => 'Amritsar', 'abbreviation' => 'ASR'],
        ['city' => 'Navi Mumbai', 'abbreviation' => 'NVM'],
        ['city' => 'Allahabad', 'abbreviation' => 'ALD']
    ],
    'medical-history' =>[
        'Diabetes',
        'Blood Pressure',
        'Other'
    ],
    'relations' =>[
        'Father',
        'Mother',
        'Sister',
        'Brother',
        'GrandFather',
        'GrandMother',
        'Son',
        'Daughter',
        'Other'
    ],
    'bloodgroup' =>[
        'A+',
        'B+',
        'Ab+',
        'O+',
        'A-',
        'B-',
        'Ab-',
        'O-'
    ],
    'educations' =>[
        'No formal education',
        'Primary education',
        'Secondary education or high school',
        'Graduation',
        'Master\'s degree',
        'Doctorate or higher',
    ],
    'perpage'=>10,
    'roles' => [
        "superadmin"=>'super-admin',
        "captain"=>'captain',
        "admin"=>'admin',
        "member"=>'member',
    ]


];
